### ISSUE TITLE
CONTAS A PAGAR - Pagamentos de prêmios instantâneos (PIX)

### ISSUE THREAD

**Issue by tatianawurmb** [tatianawurmb/Integra-o-Totvs#22]

**Comment by tatianawurmb** [comment]
Reunião com a Leticia em 23/12/2024, entendimento do processo em linhas gerais.
Integração do API com a plataforma de comercialização do produto é com o Binotto
Integração com o banco para gerar a remessa de PIX sem a necessidade de passar pelo contas a pagar é com o Neri.
Verificar a questão da validação dos documentos para sorteios abaixo de 2 mil. Passa pela IA ou não? @claudioasj tens essa informação?

**Comment by tatianawurmb** [comment]
Em reunião com equipe de DEV ficou decidido por consenso que para realizar INTEGRAÇÃO do FINANCEIRO SGS/TOTVS nenhuma ação é necessária, o entendimento está claro pra todos.
Exceto a questão do comprovante bancário de pagamento do PIX. Foi criada uma issue específica para tratar do assunto e irão envolver o Neri.
>> Decidimos não fechar esta issue pois no futuro será necessário revisitar esse assunto para realizar o pagamento dos PIX instantâneos via COREON.

**Comment by Jocemar-schmitt** [comment]
Não tendo ação a ser realizada referente a integração PIX com a TOTVS, esta issue pode ser encerrada pois para tratamento do Recebimento e Pagamento de PIX via COREON está aberta a issue 34.
